// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package service

import (
	"github.com/pwestlake/portal/lambda/covid19/summary/pkg/db"
)

// Injectors from wire.go:

func InitializeCovid19DataService() Covid19DataServiceInterface {
	covid19SummaryItemDao := db.NewCovid19SummaryItemDao()
	covid19DataService := NewCovid19DataService(covid19SummaryItemDao)
	return covid19DataService
}
