// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package service

import (
	"github.com/pwestlake/portal/lambda/covid19/region/pkg/db"
)

// Injectors from wire.go:

func InitializeRegionService() RegionServiceInterface {
	regionDao := db.NewRegionDao()
	regionServiceInterface := NewRegionService(regionDao)
	return regionServiceInterface
}

// wire.go:

type dummyService struct {
	regionDao db.RegionDao
}

// GetRegionNames ...
// Dummy method
func (s *dummyService) GetRegionNames() (*[]string, error) {
	return nil, nil
}
