// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package service

import (
	"github.com/pwestlake/portal/lambda/covid19/covid19data/pkg/db"
	"github.com/pwestlake/portal/lambda/covid19/covid19data/pkg/domain"
)

// Injectors from wire.go:

func InitializeCovid19DataService() Covid19DataServiceInterface {
	covid19DataDao := db.NewCovid19DataDao()
	covid19DataServiceInterface := NewCovid19DataService(covid19DataDao)
	return covid19DataServiceInterface
}

// wire.go:

type dummyService struct {
	covid19DataDao db.Covid19DataDao
}

// GetDataForRegion ...
// Dummy method
func (s *dummyService) GetDataForRegion(regionName string) (*[]domain.Covid19DataItem, error) {
	return nil, nil
}
