// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package service

import (
	"github.com/pwestlake/portal/lambda/covid19/preferences/pkg/db"
)

// Injectors from wire.go:

func InitializeUserService() UserServiceInterface {
	userPreferenceDao := db.NewUserPreferenceDao()
	userServiceInterface := NewUserService(userPreferenceDao)
	return userServiceInterface
}

// wire.go:

type dummyService struct {
	userPreferenceDao db.UserPreferenceDao
}

// GetUserPreference ...
// Dummy method
func (s *dummyService) GetUserPreference(userID string, key string, userPreference *db.UserPreference) error {
	return nil
}

// PutUserPreference ...
// Dummy method
func (s *dummyService) PutUserPreference(userPreference *db.UserPreference) error {
	return s.userPreferenceDao.PutUserPreference(userPreference)
}
