// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package service

import (
	"github.com/pwestlake/portal/lambda/equity-fund/equitycatalog/pkg/db"
)

// Injectors from wire.go:

func InitializeEquityCatalogService() EquityCatalogService {
	equityCatalogItemDAO := db.NewEquityCatalogItemDAO()
	equityCatalogService := NewEquityCatalogService(equityCatalogItemDAO)
	return equityCatalogService
}
