version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "portal"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1kmx58y5898fl"
s3_prefix = "portal"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DbRegion=\"eu-west-2\" DynamoDbEndpoint=\"https://dynamodb.eu-west-2.amazonaws.com\""
