// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package service

import (
	"github.com/pwestlake/portal/lambda/equity-fund/news/pkg/db"
)

// Injectors from wire.go:

func InitializeNewsService() NewsService {
	newsItemDAO := db.NewNewsItemDAO()
	newsService := NewNewsService(newsItemDAO)
	return newsService
}
