// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package service

import (
	"github.com/pwestlake/portal/lambda/equity-fund/eod/pkg/db"
)

// Injectors from wire.go:

func InitializeEndOfDayService() EndOfDayService {
	endOfDayItemDAO := db.NewEndOfDayItemDAO()
	endOfDayService := NewEndOfDayService(endOfDayItemDAO)
	return endOfDayService
}
