// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package service

import (
	db2 "github.com/pwestlake/portal/lambda/equity-fund/eod/pkg/db"
	service2 "github.com/pwestlake/portal/lambda/equity-fund/eod/pkg/service"
	"github.com/pwestlake/portal/lambda/equity-fund/equitycatalog/pkg/db"
	"github.com/pwestlake/portal/lambda/equity-fund/equitycatalog/pkg/service"
	db3 "github.com/pwestlake/portal/lambda/equity-fund/news/pkg/db"
	service3 "github.com/pwestlake/portal/lambda/equity-fund/news/pkg/service"
)

// Injectors from wire.go:

func InitializeEODUpdateService() EODUpdateService {
	equityCatalogItemDAO := db.NewEquityCatalogItemDAO()
	equityCatalogService := service.NewEquityCatalogService(equityCatalogItemDAO)
	endOfDayItemDAO := db2.NewEndOfDayItemDAO()
	endOfDayService := service2.NewEndOfDayService(endOfDayItemDAO)
	yahooService := NewYahooService()
	newsItemDAO := db3.NewNewsItemDAO()
	newsService := service3.NewNewsService(newsItemDAO)
	lseService := NewLSEService()
	eodUpdateService := NewEODUpdateService(equityCatalogService, endOfDayService, yahooService, newsService, lseService)
	return eodUpdateService
}

func InitializeYahooService() YahooService {
	yahooService := NewYahooService()
	return yahooService
}

func InitializeLSEService() LSEService {
	lseService := NewLSEService()
	return lseService
}

func InitializeNLPService() NLPService {
	nlpService := NewNLPService()
	return nlpService
}
